image: gitpod/workspace-dotnet

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y dotnet-sdk-8.0

vscode:
  extensions:
    - muhammad-sammy.csharp
    - ms-dotnettools.vscode-dotnet-runtime
